### PR TITLE
infer handle data fn and curl spec fn

### PR DESCRIPTION
**Pull request by jesses-code-adventures**
felt a bit nicer to not need to specify these in the lazy config, pls reject if it was designed this way for reasons i didn't see.

### CODE REVIEW

**Review by yacineMTB — CHANGES_REQUESTED** [review]
Thank you for the PR. This is fair! But my preference is to make things as explicit as possible in the config, given the APIs differ so much from provider to provider. Inferring seems a bit lurky, would rather just have it be explicit by the configurer

**Comment by yacineMTB** [comment]
request changes because do you think we can get a PR to put in to have the readme to instruct where to put the API keys?

**Comment by jesses-code-adventures** [comment]
All good and I get that! Have made the changes to the readme re the API keys, any other changes please let me know

**Comment by yacineMTB** [comment]
image
i merged though! also i forgot to change pr name. oops. hatever. closing. but closing as merged!

**Pull request closed without merging**
